# What is the goal of your workflow
# Goal: whenever someone changes the python code
# the linter will check if the syntax, format, indentation(linting) is correct or not
name: Auto Linter

on:
  push:
    paths: "**/*.py"


jobs:
  code-linting:
    runs-on: ubuntu-latest
    # this step will automatically clone the  code of the current bracnch into the runner
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v4
    # This step will install python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
# this step will install the linting tool
      - name: Install linter
        run: pip install ruff

# This step will run the linter
      - name: Check the files the linting
        run: ruff check .
